services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  metastore:
    image: apache/hive:3.1.3
    container_name: hive-metastore
    environment:
      SERVICE_NAME: metastore
      HIVE_METASTORE_USER: hive
      HIVE_METASTORE_PASSWORD: hive
      HIVE_METASTORE_DB: metastore
    ports:
      - "9083:9083"
    depends_on:
      - postgres

  trino:
    image: trinodb/trino:latest
    container_name: trino
    ports:
      - "5050:8080"
    volumes:
      - ./trino-config:/etc/trino
    depends_on:
      - metastore

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_pw
    volumes:
      - C:\Users\micro\Documents\Data\minio:/data
    command: server /data --console-address ":9090"


  # iceberg:
  #   image: apache/iceberg
  #   container_name: iceberg
  #   depends_on:
  #     - metastore
  #     - trino

  airflow:
    image: apache/airflow:latest
    container_name: airflow
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    volumes:
      - airflow_data:/opt/airflow

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:latest
    container_name: dbt
    volumes:
      - ./dbt:/usr/app/dbt
    depends_on:
      - trino
      - postgres

  openmetadata:
    image: openmetadata/server:latest
    container_name: openmetadata
    ports:
      - "8585:8585"
    environment:
      - OM_DATABASE_HOST=postgres
      - OM_DATABASE_USER=airflow
      - OM_DATABASE_PASSWORD=airflow
      - OM_DATABASE_DB=airflow
    depends_on:
      - postgres
      - trino
      - metastore

volumes:
  postgres_data:
  airflow_data:
  trino-config:
  dbt:
  hive_metastore_data:
